---
# Copyright 2018--present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Values file for voltha log aggregation infra
# NOTE: must start this chart with the name "logging":
#   helm install -n logging voltha-logging
# ortherwise the elasticsearch hostname won't work properly in the other containers

# elasticstack config
# ref: https://github.com/helm/charts/tree/master/stable/elasticsearch
elasticsearch:
  client:
    serviceType: "NodePort"
  master:
    persistence:
      storageClass: "local-ssd"
      size: "5Gi"
  data:
    persistence:
      storageClass: "local-hdd"
      size: "10Gi"

# kibana config
# ref: https://github.com/helm/charts/tree/master/stable/kibana
kibana:

  service:
    type: "NodePort"
    nodePort: 30601
  env:
     ELASTICSEARCH_HOSTS: "http://logging-elasticsearch-client:9200"


# fluentd-elasticsearch config
# ref: https://github.com/helm/charts/tree/master/stable/fluentd-elasticsearch
# forwards k8s logs from nodes to elasticsearch
fluentd-elasticsearch:
  elasticsearch:
    host: "logging-elasticsearch-client"

  configMaps:
    containers.input.conf: |
      <match fluent.**>
        @type null
      </match> 

      <source>
        @type tail
        path /var/log/containers/*.log
        pos_file fluentd-docker.pos
        read_from_head true
        tag kubernetes.*
        <parse>
          @type multi_format
          <pattern>
            format json
            time_key time
            time_type string
            time_format "%Y-%m-%dT%H:%M:%S.%NZ"
            keep_time_key false
          </pattern>
          <pattern>
            format regexp
            expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
            time_format '%Y-%m-%dT%H:%M:%S.%N%:z'
            keep_time_key false
          </pattern>
        </parse>
      </source>

       <match kubernetes.var.log.containers.**fluentd**.log>
         @type null
       </match>

       <match kubernetes.var.log.containers.**kube-system**.log>
         @type null
       </match>

    system.input.conf: |
       <match kubernetes.var.log.containers.**fluentd**.log>
         @type null
       </match>

       <match kubernetes.var.log.containers.**kube-system**.log>
         @type null
       </match>

    output.conf: |
       # Enriches records with Kubernetes metadata
       <filter kubernetes.**>
         @type kubernetes_metadata
       </filter>

       <match **>
         @id elasticsearch
         @type elasticsearch
         @log_level info
         include_tag_key true
         type_name _doc
         host "logging-elasticsearch-client" 
         port "9200"
         scheme "http"
         logstash_format true
         logstash_prefix "logstash"
         reconnect_on_error true
         <buffer>
           @type file
           path /var/log/fluentd-buffers/kubernetes.system.buffer
           flush_mode interval
           retry_type exponential_backoff
           flush_thread_count 2
           flush_interval 5s
           retry_forever
           retry_max_interval 30
           chunk_limit_size 20M
           queue_limit_length 16 
           overflow_action block
         </buffer>
       </match>
